version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eth_indexer_db
    environment:
      POSTGRES_USER: indexer_user
      POSTGRES_PASSWORD: indexer_password
      POSTGRES_DB: eth_indexer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres 
      -c shared_buffers=256MB 
      -c max_connections=50
      -c synchronous_commit=off
    # synchronous_commit=off отключает немедленный сброс логов на диск ради скорости.
    # Для учебного полигона и ETL-процессов это существенно ускорит Bulk Insert.

volumes:
  pgdata: